// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlbxdswayzjckmuibcfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sYnhkc3dheXpqY2ttdWliY2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NjMyNzcsImV4cCI6MjA2OTQzOTI3N30.zO_Zq3uYDXQ1Hsu6VlP0Lb6JQWV54SbqYji92Zzsnck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});